In [183]:
##### part1: import pandas ###########
import pandas as pd

In [103]:
df = pd.read_csv('Automobile_data.csv')

In [105]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [31]:
##### part2:DataFrame and Series Basics - Selecting Rows and Columns #######
#accessing series (column)
## 1) []
df['make']

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: object

In [47]:
## 2) using dot .
df.bore

0      3.47
1      3.47
2      2.68
3      3.19
4      3.19
       ...
200    3.78
201    3.78
202    3.58
203    3.01
204    3.78
Name: bore, Length: 205, dtype: object

In [57]:
# #accessing series (row)
df.loc[4]

symboling                2
normalized-losses      164
make                  audi
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           4wd
engine-location      front
wheel-base            99.4
length               176.6
width                 66.4
height                54.3
curb-weight           2824
engine-type            ohc
num-of-cylinders      five
engine-size            136
fuel-system           mpfi
bore                  3.19
stroke                 3.4
compression-ratio      8.0
horsepower             115
peak-rpm              5500
city-mpg                18
highway-mpg             22
price                17450
Name: 4, dtype: object

In [65]:
# accessing Dataframe (column)
df[['make','fuel-type']]

            make fuel-type
0    alfa-romero       gas
1    alfa-romero       gas
2    alfa-romero       gas
3           audi       gas
4           audi       gas
..           ...       ...
200        volvo       gas
201        volvo       gas
202        volvo       gas
203        volvo    diesel
204        volvo       gas

[205 rows x 2 columns]

In [67]:
# accessing Dataframe (row)
df.iloc[0:2]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500

In [141]:
##### part3: indexes How to Set, Reset, and Use Indexes
# 1. Default Index
data = {'symboling': ['3', '3', '1'], 'make': ['alfa-romero', 'alfa-romero', 'alfa-romero'], 'body-style': ['convertible', 'convertible', 'hatchback']}
df = pd.DataFrame(data)
print(df)

  symboling         make   body-style
0         3  alfa-romero  convertible
1         3  alfa-romero  convertible
2         1  alfa-romero    hatchback

In [149]:
# 2. Custom Index
df_custom_index = df.set_index('symboling')
print(df_custom_index)

                  make   body-style
symboling
3          alfa-romero  convertible
3          alfa-romero  convertible
1          alfa-romero    hatchback

In [159]:
# 3. Setting Index When Reading CSV
df_from_csv = pd.read_csv("Automobile_data.csv", index_col="make")
print(df_from_csv)

             symboling normalized-losses fuel-type aspiration num-of-doors  \
make
alfa-romero          3                 ?       gas        std          two
alfa-romero          3                 ?       gas        std          two
alfa-romero          1                 ?       gas        std          two
audi                 2               164       gas        std         four
audi                 2               164       gas        std         four
...                ...               ...       ...        ...          ...
volvo               -1                95       gas        std         four
volvo               -1                95       gas      turbo         four
volvo               -1                95       gas        std         four
volvo               -1                95    diesel      turbo         four
volvo               -1                95       gas      turbo         four

              body-style drive-wheels engine-location  wheel-base  length  \
make
alfa-romero  convertible          rwd           front        88.6   168.8
alfa-romero  convertible          rwd           front        88.6   168.8
alfa-romero    hatchback          rwd           front        94.5   171.2
audi               sedan          fwd           front        99.8   176.6
audi               sedan          4wd           front        99.4   176.6
...                  ...          ...             ...         ...     ...
volvo              sedan          rwd           front       109.1   188.8
volvo              sedan          rwd           front       109.1   188.8
volvo              sedan          rwd           front       109.1   188.8
volvo              sedan          rwd           front       109.1   188.8
volvo              sedan          rwd           front       109.1   188.8

             ...  engine-size  fuel-system  bore stroke compression-ratio  \
make         ...
alfa-romero  ...          130         mpfi  3.47   2.68               9.0
alfa-romero  ...          130         mpfi  3.47   2.68               9.0
alfa-romero  ...          152         mpfi  2.68   3.47               9.0
audi         ...          109         mpfi  3.19    3.4              10.0
audi         ...          136         mpfi  3.19    3.4               8.0
...          ...          ...          ...   ...    ...               ...
volvo        ...          141         mpfi  3.78   3.15               9.5
volvo        ...          141         mpfi  3.78   3.15               8.7
volvo        ...          173         mpfi  3.58   2.87               8.8
volvo        ...          145          idi  3.01    3.4              23.0
volvo        ...          141         mpfi  3.78   3.15               9.5

             horsepower peak-rpm city-mpg highway-mpg  price
make
alfa-romero         111     5000       21          27  13495
alfa-romero         111     5000       21          27  16500
alfa-romero         154     5000       19          26  16500
audi                102     5500       24          30  13950
audi                115     5500       18          22  17450
...                 ...      ...      ...         ...    ...
volvo               114     5400       23          28  16845
volvo               160     5300       19          25  19045
volvo               134     5500       18          23  21485
volvo               106     4800       26          27  22470
volvo               114     5400       19          25  22625

[205 rows x 25 columns]

In [171]:
# 4. Accessing Rows Using Indexers
print(df_from_csv.loc['volvo'])

       symboling normalized-losses fuel-type aspiration num-of-doors  \
make
volvo         -2               103       gas        std         four
volvo         -1                74       gas        std         four
volvo         -2               103       gas        std         four
volvo         -1                74       gas        std         four
volvo         -2               103       gas      turbo         four
volvo         -1                74       gas      turbo         four
volvo         -1                95       gas        std         four
volvo         -1                95       gas      turbo         four
volvo         -1                95       gas        std         four
volvo         -1                95    diesel      turbo         four
volvo         -1                95       gas      turbo         four

      body-style drive-wheels engine-location  wheel-base  length  ...  \
make                                                               ...
volvo      sedan          rwd           front       104.3   188.8  ...
volvo      wagon          rwd           front       104.3   188.8  ...
volvo      sedan          rwd           front       104.3   188.8  ...
volvo      wagon          rwd           front       104.3   188.8  ...
volvo      sedan          rwd           front       104.3   188.8  ...
volvo      wagon          rwd           front       104.3   188.8  ...
volvo      sedan          rwd           front       109.1   188.8  ...
volvo      sedan          rwd           front       109.1   188.8  ...
volvo      sedan          rwd           front       109.1   188.8  ...
volvo      sedan          rwd           front       109.1   188.8  ...
volvo      sedan          rwd           front       109.1   188.8  ...

       engine-size  fuel-system  bore stroke compression-ratio  horsepower  \
make
volvo          141         mpfi  3.78   3.15               9.5         114
volvo          141         mpfi  3.78   3.15               9.5         114
volvo          141         mpfi  3.78   3.15               9.5         114
volvo          141         mpfi  3.78   3.15               9.5         114
volvo          130         mpfi  3.62   3.15               7.5         162
volvo          130         mpfi  3.62   3.15               7.5         162
volvo          141         mpfi  3.78   3.15               9.5         114
volvo          141         mpfi  3.78   3.15               8.7         160
volvo          173         mpfi  3.58   2.87               8.8         134
volvo          145          idi  3.01    3.4              23.0         106
volvo          141         mpfi  3.78   3.15               9.5         114

      peak-rpm city-mpg highway-mpg  price
make
volvo     5400       23          28  12940
volvo     5400       23          28  13415
volvo     5400       24          28  15985
volvo     5400       24          28  16515
volvo     5100       17          22  18420
volvo     5100       17          22  18950
volvo     5400       23          28  16845
volvo     5300       19          25  19045
volvo     5500       18          23  21485
volvo     4800       26          27  22470
volvo     5400       19          25  22625

[11 rows x 25 columns]

In [177]:
# 5. Accessing Specific Values
make_of_body_style = df_from_csv.loc['volvo', 'body-style']
print(make_of_body_style)

make
volvo    sedan
volvo    wagon
volvo    sedan
volvo    wagon
volvo    sedan
volvo    wagon
volvo    sedan
volvo    sedan
volvo    sedan
volvo    sedan
volvo    sedan
Name: body-style, dtype: object

In [181]:
# 6. Resetting Index
df_reset = df_from_csv.reset_index()
print(df_reset)

            make  symboling normalized-losses fuel-type aspiration  \
0    alfa-romero          3                 ?       gas        std
1    alfa-romero          3                 ?       gas        std
2    alfa-romero          1                 ?       gas        std
3           audi          2               164       gas        std
4           audi          2               164       gas        std
..           ...        ...               ...       ...        ...
200        volvo         -1                95       gas        std
201        volvo         -1                95       gas      turbo
202        volvo         -1                95       gas        std
203        volvo         -1                95    diesel      turbo
204        volvo         -1                95       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111
1            130         mpfi  3.47    2.68               9.0        111
2            152         mpfi  2.68    3.47               9.0        154
3            109         mpfi  3.19     3.4              10.0        102
4            136         mpfi  3.19     3.4               8.0        115
..           ...          ...   ...     ...               ...        ...
200          141         mpfi  3.78    3.15               9.5        114
201          141         mpfi  3.78    3.15               8.7        160
202          173         mpfi  3.58    2.87               8.8        134
203          145          idi  3.01     3.4              23.0        106
204          141         mpfi  3.78    3.15               9.5        114

     peak-rpm city-mpg highway-mpg  price
0        5000       21          27  13495
1        5000       21          27  16500
2        5000       19          26  16500
3        5500       24          30  13950
4        5500       18          22  17450
..        ...      ...         ...    ...
200      5400       23          28  16845
201      5300       19          25  19045
202      5500       18          23  21485
203      4800       26          27  22470
204      5400       19          25  22625

[205 rows x 26 columns]

In [203]:
###### part4:  Filtering - Using Conditionals to Filter Rows and Columns #########
# 1. Creating a Filter Mask
df_from_csv = pd.read_csv("Automobile_data.csv")
fltr = df_from_csv['make'] == 'audi'
print(fltr)

0      False
1      False
2      False
3       True
4       True
       ...
200    False
201    False
202    False
203    False
204    False
Name: make, Length: 205, dtype: bool

In [205]:
#  2. Applying the Filter
print(df_from_csv[fltr])

   symboling normalized-losses  make fuel-type aspiration num-of-doors  \
3          2               164  audi       gas        std         four
4          2               164  audi       gas        std         four
5          2                 ?  audi       gas        std          two
6          1               158  audi       gas        std         four
7          1                 ?  audi       gas        std         four
8          1               158  audi       gas      turbo         four
9          0                 ?  audi       gas      turbo          two

  body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
3      sedan          fwd           front        99.8  ...          109
4      sedan          4wd           front        99.4  ...          136
5      sedan          fwd           front        99.8  ...          136
6      sedan          fwd           front       105.8  ...          136
7      wagon          fwd           front       105.8  ...          136
8      sedan          fwd           front       105.8  ...          131
9  hatchback          4wd           front        99.5  ...          131

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
3         mpfi  3.19     3.4              10.0        102      5500       24
4         mpfi  3.19     3.4               8.0        115      5500       18
5         mpfi  3.19     3.4               8.5        110      5500       19
6         mpfi  3.19     3.4               8.5        110      5500       19
7         mpfi  3.19     3.4               8.5        110      5500       19
8         mpfi  3.13     3.4               8.3        140      5500       17
9         mpfi  3.13     3.4               7.0        160      5500       16

  highway-mpg  price
3          30  13950
4          22  17450
5          25  15250
6          25  17710
7          25  18920
8          20  23875
9          22      ?

[7 rows x 26 columns]

In [213]:
# 3. Selecting Specific Columns with .loc
print(df_from_csv.loc[fltr, ['make', 'aspiration']])

   make aspiration
3  audi        std
4  audi        std
5  audi        std
6  audi        std
7  audi        std
8  audi      turbo
9  audi      turbo

In [225]:
# 4. Combining Conditions with & and |
fltr = (df_from_csv['fuel-type'] == 'gas') | (df_from_csv['drive-wheels'] == 'fwd')
print(df_from_csv.loc[fltr])

     symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?  alfa-romero       gas        std
3            2               164         audi       gas        std
4            2               164         audi       gas        std
..         ...               ...          ...       ...        ...
199         -1                74        volvo       gas      turbo
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
204         -1                95        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
199         four        wagon          rwd           front       104.3  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111
1            130         mpfi  3.47    2.68               9.0        111
2            152         mpfi  2.68    3.47               9.0        154
3            109         mpfi  3.19     3.4              10.0        102
4            136         mpfi  3.19     3.4               8.0        115
..           ...          ...   ...     ...               ...        ...
199          130         mpfi  3.62    3.15               7.5        162
200          141         mpfi  3.78    3.15               9.5        114
201          141         mpfi  3.78    3.15               8.7        160
202          173         mpfi  3.58    2.87               8.8        134
204          141         mpfi  3.78    3.15               9.5        114

     peak-rpm city-mpg highway-mpg  price
0        5000       21          27  13495
1        5000       21          27  16500
2        5000       19          26  16500
3        5500       24          30  13950
4        5500       18          22  17450
..        ...      ...         ...    ...
199      5100       17          22  18950
200      5400       23          28  16845
201      5300       19          25  19045
202      5500       18          23  21485
204      5400       19          25  22625

[194 rows x 26 columns]

In [231]:
#  5. Negating a Filter with ~

negated = ~(df_from_csv['make'] == 'audi')
print(df_from_csv.loc[negated])

     symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?  alfa-romero       gas        std
10           2               192          bmw       gas        std
11           0               192          bmw       gas        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
10           two        sedan          rwd           front       101.2  ...
11          four        sedan          rwd           front       101.2  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111
1            130         mpfi  3.47    2.68               9.0        111
2            152         mpfi  2.68    3.47               9.0        154
10           108         mpfi   3.5     2.8               8.8        101
11           108         mpfi   3.5     2.8               8.8        101
..           ...          ...   ...     ...               ...        ...
200          141         mpfi  3.78    3.15               9.5        114
201          141         mpfi  3.78    3.15               8.7        160
202          173         mpfi  3.58    2.87               8.8        134
203          145          idi  3.01     3.4              23.0        106
204          141         mpfi  3.78    3.15               9.5        114

     peak-rpm city-mpg highway-mpg  price
0        5000       21          27  13495
1        5000       21          27  16500
2        5000       19          26  16500
10       5800       23          29  16430
11       5800       23          29  16925
..        ...      ...         ...    ...
200      5400       23          28  16845
201      5300       19          25  19045
202      5500       18          23  21485
203      4800       26          27  22470
204      5400       19          25  22625

[198 rows x 26 columns]

In [249]:
# 6. Filtering with String Methods: .str.contains()
fltr = df_from_csv['make'].str.contains('aud', na=False)
print(df_from_csv.loc[fltr])

   symboling normalized-losses  make fuel-type aspiration num-of-doors  \
3          2               164  audi       gas        std         four
4          2               164  audi       gas        std         four
5          2                 ?  audi       gas        std          two
6          1               158  audi       gas        std         four
7          1                 ?  audi       gas        std         four
8          1               158  audi       gas      turbo         four
9          0                 ?  audi       gas      turbo          two

  body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
3      sedan          fwd           front        99.8  ...          109
4      sedan          4wd           front        99.4  ...          136
5      sedan          fwd           front        99.8  ...          136
6      sedan          fwd           front       105.8  ...          136
7      wagon          fwd           front       105.8  ...          136
8      sedan          fwd           front       105.8  ...          131
9  hatchback          4wd           front        99.5  ...          131

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
3         mpfi  3.19     3.4              10.0        102      5500       24
4         mpfi  3.19     3.4               8.0        115      5500       18
5         mpfi  3.19     3.4               8.5        110      5500       19
6         mpfi  3.19     3.4               8.5        110      5500       19
7         mpfi  3.19     3.4               8.5        110      5500       19
8         mpfi  3.13     3.4               8.3        140      5500       17
9         mpfi  3.13     3.4               7.0        160      5500       16

  highway-mpg  price
3          30  13950
4          22  17450
5          25  15250
6          25  17710
7          25  18920
8          20  23875
9          22      ?

[7 rows x 26 columns]

In [253]:
#### part5: Updating Rows and Columns - Modifying Data Within DataFrames #######

# 1. Updating Columns in a DataFrame
##  View Existing Column Names
df = df_from_csv
print(df.columns)

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [259]:
##  Rename All Columns
df.column = ['Symboling', 'Normalized-Losses']
print(df.head())

   symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two
1          3                 ?  alfa-romero       gas        std          two
2          1                 ?  alfa-romero       gas        std          two
3          2               164         audi       gas        std         four
4          2               164         audi       gas        std         four

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130
1  convertible          rwd           front        88.6  ...          130
2    hatchback          rwd           front        94.5  ...          152
3        sedan          fwd           front        99.8  ...          109
4        sedan          4wd           front        99.4  ...          136

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21
1         mpfi  3.47    2.68               9.0        111      5000       21
2         mpfi  2.68    3.47               9.0        154      5000       19
3         mpfi  3.19     3.4              10.0        102      5500       24
4         mpfi  3.19     3.4               8.0        115      5500       18

  highway-mpg  price
0          27  13495
1          27  16500
2          26  16500
3          30  13950
4          22  17450

[5 rows x 26 columns]

In [265]:
## Modify Column Names with String Methods

# Replace spaces with underscores
df.columns = df.columns.str.replace('-', '_')
print(df.columns)

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'num_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'num_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [271]:
df.rename(columns={'symboling': 'Symboling', 'normalized_losses': 'Normalized_Nosses'}, inplace=True)

print(df.column)

['Symboling', 'Normalized-Losses']

In [277]:
#  2. Updating Rows
## Update a Single Cell
df.loc[2,'make'] = 'BMW'

print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?          BMW       gas        std
3            2               164         audi       gas        std
4            2               164         audi       gas        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

    num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111
1            130         mpfi  3.47    2.68               9.0        111
2            152         mpfi  2.68    3.47               9.0        154
3            109         mpfi  3.19     3.4              10.0        102
4            136         mpfi  3.19     3.4               8.0        115
..           ...          ...   ...     ...               ...        ...
200          141         mpfi  3.78    3.15               9.5        114
201          141         mpfi  3.78    3.15               8.7        160
202          173         mpfi  3.58    2.87               8.8        134
203          145          idi  3.01     3.4              23.0        106
204          141         mpfi  3.78    3.15               9.5        114

     peak_rpm city_mpg highway_mpg  price
0        5000       21          27  13495
1        5000       21          27  16500
2        5000       19          26  16500
3        5500       24          30  13950
4        5500       18          22  17450
..        ...      ...         ...    ...
200      5400       23          28  16845
201      5300       19          25  19045
202      5500       18          23  21485
203      4800       26          27  22470
204      5400       19          25  22625

[205 rows x 26 columns]

In [289]:
## Update Multiple Columns in One Row
df.loc[3,['fuel_type', 'num_of_doors']] = ['elec', 'four']

print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?          BMW       gas        std
3            2               164         audi      elec        std
4            2               164         audi       gas        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

    num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     bore  stroke  compression_ratio  horsepower peak_rpm city_mpg  \
0    3.47    2.68                9.0         111     5000       21
1    3.47    2.68                9.0         111     5000       21
2    2.68    3.47                9.0         154     5000       19
3    3.19     3.4               10.0         102     5500       24
4    3.19     3.4                8.0         115     5500       18
..    ...     ...                ...         ...      ...      ...
200  3.78    3.15                9.5         114     5400       23
201  3.78    3.15                8.7         160     5300       19
202  3.58    2.87                8.8         134     5500       18
203  3.01     3.4               23.0         106     4800       26
204  3.78    3.15                9.5         114     5400       19

     highway_mpg  price fuel-type num-of-doors
0             27  13495       NaN          NaN
1             27  16500      elec         four
2             26  16500       NaN          NaN
3             30  13950      elec         four
4             22  17450       NaN          NaN
..           ...    ...       ...          ...
200           28  16845       NaN          NaN
201           25  19045       NaN          NaN
202           23  21485       NaN          NaN
203           27  22470       NaN          NaN
204           25  22625       NaN          NaN

[205 rows x 28 columns]

In [293]:
## Use Filter to Update Rows
fltr = (df['make'] == "audi")
df.loc[fltr, 'fuel_type'] = 'elec'

print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?          BMW       gas        std
3            2               164         audi      elec        std
4            2               164         audi      elec        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

    num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     bore  stroke  compression_ratio  horsepower peak_rpm city_mpg  \
0    3.47    2.68                9.0         111     5000       21
1    3.47    2.68                9.0         111     5000       21
2    2.68    3.47                9.0         154     5000       19
3    3.19     3.4               10.0         102     5500       24
4    3.19     3.4                8.0         115     5500       18
..    ...     ...                ...         ...      ...      ...
200  3.78    3.15                9.5         114     5400       23
201  3.78    3.15                8.7         160     5300       19
202  3.58    2.87                8.8         134     5500       18
203  3.01     3.4               23.0         106     4800       26
204  3.78    3.15                9.5         114     5400       19

     highway_mpg  price fuel-type num-of-doors
0             27  13495       NaN          NaN
1             27  16500      elec         four
2             26  16500       NaN          NaN
3             30  13950      elec         four
4             22  17450       NaN          NaN
..           ...    ...       ...          ...
200           28  16845       NaN          NaN
201           25  19045       NaN          NaN
202           23  21485       NaN          NaN
203           27  22470       NaN          NaN
204           25  22625       NaN          NaN

[205 rows x 28 columns]

In [301]:
# 3.Advanced Methods: apply, map, applymap, replace
## .apply() on Series
df['make_length'] = df['make'].apply(len)

print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?          BMW       gas        std
3            2               164         audi      elec        std
4            2               164         audi      elec        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

    num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     stroke  compression_ratio  horsepower  peak_rpm city_mpg highway_mpg  \
0      2.68                9.0         111      5000       21          27
1      2.68                9.0         111      5000       21          27
2      3.47                9.0         154      5000       19          26
3       3.4               10.0         102      5500       24          30
4       3.4                8.0         115      5500       18          22
..      ...                ...         ...       ...      ...         ...
200    3.15                9.5         114      5400       23          28
201    3.15                8.7         160      5300       19          25
202    2.87                8.8         134      5500       18          23
203     3.4               23.0         106      4800       26          27
204    3.15                9.5         114      5400       19          25

     price fuel-type num-of-doors make_length
0    13495       NaN          NaN          11
1    16500      elec         four          11
2    16500       NaN          NaN           3
3    13950      elec         four           4
4    17450       NaN          NaN           4
..     ...       ...          ...         ...
200  16845       NaN          NaN           5
201  19045       NaN          NaN           5
202  21485       NaN          NaN           5
203  22470       NaN          NaN           5
204  22625       NaN          NaN           5

[205 rows x 29 columns]

In [309]:
## .apply() with Custom Function
def make_upper(text):
    return text.upper()

df['make'] = df['make'].apply(make_upper)

print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  ALFA-ROMERO       gas        std
1            3                 ?  ALFA-ROMERO       gas        std
2            1                 ?          BMW       gas        std
3            2               164         AUDI      elec        std
4            2               164         AUDI      elec        std
..         ...               ...          ...       ...        ...
200         -1                95        VOLVO       gas        std
201         -1                95        VOLVO       gas      turbo
202         -1                95        VOLVO       gas        std
203         -1                95        VOLVO    diesel      turbo
204         -1                95        VOLVO       gas      turbo

    num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     stroke  compression_ratio  horsepower  peak_rpm city_mpg highway_mpg  \
0      2.68                9.0         111      5000       21          27
1      2.68                9.0         111      5000       21          27
2      3.47                9.0         154      5000       19          26
3       3.4               10.0         102      5500       24          30
4       3.4                8.0         115      5500       18          22
..      ...                ...         ...       ...      ...         ...
200    3.15                9.5         114      5400       23          28
201    3.15                8.7         160      5300       19          25
202    2.87                8.8         134      5500       18          23
203     3.4               23.0         106      4800       26          27
204    3.15                9.5         114      5400       19          25

     price fuel-type num-of-doors make_length
0    13495       NaN          NaN          11
1    16500      elec         four          11
2    16500       NaN          NaN           3
3    13950      elec         four           4
4    17450       NaN          NaN           4
..     ...       ...          ...         ...
200  16845       NaN          NaN           5
201  19045       NaN          NaN           5
202  21485       NaN          NaN           5
203  22470       NaN          NaN           5
204  22625       NaN          NaN           5

[205 rows x 29 columns]

In [319]:
## .applymap() on DataFrame

df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)
print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?          bmw       gas        std
3            2               164         audi      elec        std
4            2               164         audi      elec        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

    num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     stroke  compression_ratio  horsepower  peak_rpm city_mpg highway_mpg  \
0      2.68                9.0         111      5000       21          27
1      2.68                9.0         111      5000       21          27
2      3.47                9.0         154      5000       19          26
3       3.4               10.0         102      5500       24          30
4       3.4                8.0         115      5500       18          22
..      ...                ...         ...       ...      ...         ...
200    3.15                9.5         114      5400       23          28
201    3.15                8.7         160      5300       19          25
202    2.87                8.8         134      5500       18          23
203     3.4               23.0         106      4800       26          27
204    3.15                9.5         114      5400       19          25

     price fuel-type num-of-doors make_length
0    13495       NaN          NaN          11
1    16500      elec         four          11
2    16500       NaN          NaN           3
3    13950      elec         four           4
4    17450       NaN          NaN           4
..     ...       ...          ...         ...
200  16845       NaN          NaN           5
201  19045       NaN          NaN           5
202  21485       NaN          NaN           5
203  22470       NaN          NaN           5
204  22625       NaN          NaN           5

[205 rows x 29 columns]

C:\Users\user\AppData\Local\Temp\ipykernel_34496\2845414830.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [333]:
## .map() on Series

df['num_of_doors'] = df['num_of_doors'].map({'four': 4, 'two': 2})
print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?          bmw       gas        std
3            2               164         audi      elec        std
4            2               164         audi      elec        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

     num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             NaN  convertible          rwd           front        88.6  ...
1             NaN  convertible          rwd           front        88.6  ...
2             NaN    hatchback          rwd           front        94.5  ...
3             NaN        sedan          fwd           front        99.8  ...
4             NaN        sedan          4wd           front        99.4  ...
..            ...          ...          ...             ...         ...  ...
200           NaN        sedan          rwd           front       109.1  ...
201           NaN        sedan          rwd           front       109.1  ...
202           NaN        sedan          rwd           front       109.1  ...
203           NaN        sedan          rwd           front       109.1  ...
204           NaN        sedan          rwd           front       109.1  ...

     stroke  compression_ratio  horsepower  peak_rpm city_mpg highway_mpg  \
0      2.68                9.0         111      5000       21          27
1      2.68                9.0         111      5000       21          27
2      3.47                9.0         154      5000       19          26
3       3.4               10.0         102      5500       24          30
4       3.4                8.0         115      5500       18          22
..      ...                ...         ...       ...      ...         ...
200    3.15                9.5         114      5400       23          28
201    3.15                8.7         160      5300       19          25
202    2.87                8.8         134      5500       18          23
203     3.4               23.0         106      4800       26          27
204    3.15                9.5         114      5400       19          25

     price fuel-type num-of-doors make_length
0    13495       NaN          NaN          11
1    16500      elec         four          11
2    16500       NaN          NaN           3
3    13950      elec         four           4
4    17450       NaN          NaN           4
..     ...       ...          ...         ...
200  16845       NaN          NaN           5
201  19045       NaN          NaN           5
202  21485       NaN          NaN           5
203  22470       NaN          NaN           5
204  22625       NaN          NaN           5

[205 rows x 29 columns]

In [337]:
## .replace() on Series 

df['num_of_doors'] = df['num_of_doors'].replace({'four': 4, 'two': 2})
print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?          bmw       gas        std
3            2               164         audi      elec        std
4            2               164         audi      elec        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

     num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             NaN  convertible          rwd           front        88.6  ...
1             NaN  convertible          rwd           front        88.6  ...
2             NaN    hatchback          rwd           front        94.5  ...
3             NaN        sedan          fwd           front        99.8  ...
4             NaN        sedan          4wd           front        99.4  ...
..            ...          ...          ...             ...         ...  ...
200           NaN        sedan          rwd           front       109.1  ...
201           NaN        sedan          rwd           front       109.1  ...
202           NaN        sedan          rwd           front       109.1  ...
203           NaN        sedan          rwd           front       109.1  ...
204           NaN        sedan          rwd           front       109.1  ...

     stroke  compression_ratio  horsepower  peak_rpm city_mpg highway_mpg  \
0      2.68                9.0         111      5000       21          27
1      2.68                9.0         111      5000       21          27
2      3.47                9.0         154      5000       19          26
3       3.4               10.0         102      5500       24          30
4       3.4                8.0         115      5500       18          22
..      ...                ...         ...       ...      ...         ...
200    3.15                9.5         114      5400       23          28
201    3.15                8.7         160      5300       19          25
202    2.87                8.8         134      5500       18          23
203     3.4               23.0         106      4800       26          27
204    3.15                9.5         114      5400       19          25

     price fuel-type num-of-doors make_length
0    13495       NaN          NaN          11
1    16500      elec         four          11
2    16500       NaN          NaN           3
3    13950      elec         four           4
4    17450       NaN          NaN           4
..     ...       ...          ...         ...
200  16845       NaN          NaN           5
201  19045       NaN          NaN           5
202  21485       NaN          NaN           5
203  22470       NaN          NaN           5
204  22625       NaN          NaN           5

[205 rows x 29 columns]

In [343]:
#### part6: Add/Remove Rows and Columns From DataFrames #######

# Adding Columns
## 1. Concatenating Columns to Form a New One


df['make_aspiration'] = df['make'] + ' ' + df['aspiration']
print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?          bmw       gas        std
3            2               164         audi      elec        std
4            2               164         audi      elec        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

     num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             NaN  convertible          rwd           front        88.6  ...
1             NaN  convertible          rwd           front        88.6  ...
2             NaN    hatchback          rwd           front        94.5  ...
3             NaN        sedan          fwd           front        99.8  ...
4             NaN        sedan          4wd           front        99.4  ...
..            ...          ...          ...             ...         ...  ...
200           NaN        sedan          rwd           front       109.1  ...
201           NaN        sedan          rwd           front       109.1  ...
202           NaN        sedan          rwd           front       109.1  ...
203           NaN        sedan          rwd           front       109.1  ...
204           NaN        sedan          rwd           front       109.1  ...

     compression_ratio  horsepower  peak_rpm  city_mpg highway_mpg  price  \
0                  9.0         111      5000        21          27  13495
1                  9.0         111      5000        21          27  16500
2                  9.0         154      5000        19          26  16500
3                 10.0         102      5500        24          30  13950
4                  8.0         115      5500        18          22  17450
..                 ...         ...       ...       ...         ...    ...
200                9.5         114      5400        23          28  16845
201                8.7         160      5300        19          25  19045
202                8.8         134      5500        18          23  21485
203               23.0         106      4800        26          27  22470
204                9.5         114      5400        19          25  22625

     fuel-type num-of-doors make_length  make_aspiration
0          NaN          NaN          11  alfa-romero std
1         elec         four          11  alfa-romero std
2          NaN          NaN           3          bmw std
3         elec         four           4         audi std
4          NaN          NaN           4         audi std
..         ...          ...         ...              ...
200        NaN          NaN           5        volvo std
201        NaN          NaN           5      volvo turbo
202        NaN          NaN           5        volvo std
203        NaN          NaN           5      volvo turbo
204        NaN          NaN           5      volvo turbo

[205 rows x 30 columns]

In [361]:
## 2. Column Splitting using .str.split()
df[['make' , 'aspiration']] = df['make_aspiration'].str.split(' ',  expand=True)

print(df)

     Symboling Normalized_Nosses         make fuel_type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?          bmw       gas        std
3            2               164         audi      elec        std
4            2               164         audi      elec        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

     num_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             NaN  convertible          rwd           front        88.6  ...
1             NaN  convertible          rwd           front        88.6  ...
2             NaN    hatchback          rwd           front        94.5  ...
3             NaN        sedan          fwd           front        99.8  ...
4             NaN        sedan          4wd           front        99.4  ...
..            ...          ...          ...             ...         ...  ...
200           NaN        sedan          rwd           front       109.1  ...
201           NaN        sedan          rwd           front       109.1  ...
202           NaN        sedan          rwd           front       109.1  ...
203           NaN        sedan          rwd           front       109.1  ...
204           NaN        sedan          rwd           front       109.1  ...

     compression_ratio  horsepower  peak_rpm  city_mpg highway_mpg  price  \
0                  9.0         111      5000        21          27  13495
1                  9.0         111      5000        21          27  16500
2                  9.0         154      5000        19          26  16500
3                 10.0         102      5500        24          30  13950
4                  8.0         115      5500        18          22  17450
..                 ...         ...       ...       ...         ...    ...
200                9.5         114      5400        23          28  16845
201                8.7         160      5300        19          25  19045
202                8.8         134      5500        18          23  21485
203               23.0         106      4800        26          27  22470
204                9.5         114      5400        19          25  22625

     fuel-type num-of-doors make_length  make_aspiration
0          NaN          NaN          11  alfa-romero std
1         elec         four          11  alfa-romero std
2          NaN          NaN           3          bmw std
3         elec         four           4         audi std
4          NaN          NaN           4         audi std
..         ...          ...         ...              ...
200        NaN          NaN           5        volvo std
201        NaN          NaN           5      volvo turbo
202        NaN          NaN           5        volvo std
203        NaN          NaN           5      volvo turbo
204        NaN          NaN           5      volvo turbo

[205 rows x 30 columns]

In [371]:
## Removing Columns
df.drop(columns=['aspiration'], inplace=True)

KeyError: "['aspiration'] not found in axis"

In [381]:
## Adding Rows

new_row = {'Symboling ': '500', 'Normalized_Nosses': '32', 'make': 'Abiza'}
df = df.append(new_row, ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
## Removing Rows
### a) by index
df.drop(index=0, inplace=True)  

### b) Conditionally
filt = (df['make'] == 'Abiza')
df.drop(index=df[filt].index, inplace=True)

print(df)